const express = require('express')
const routerAPI = express.Router()
const { getUsersAPI, postCreateUserAPI, putUpdateUserAPI, deleteUserAPI, postUploadSingleFileAPI, postUploadMultipleFilesAPI } = require("../controllers/api.controller")
const { validateImageUpload } = require('../middleware/middleware.images')
//router.Method('.route',handler)
routerAPI.get('/users', getUsersAPI)
routerAPI.post('/users', postCreateUserAPI)
routerAPI.put('/users', putUpdateUserAPI)
routerAPI.delete('/users', deleteUserAPI)
routerAPI.post('/file', validateImageUpload, postUploadSingleFileAPI)
routerAPI.post('/files', validateImageUpload, postUploadMultipleFilesAPI)
module.exports = routerAPI;//export default